@startuml

autonumber

participant "Utilisateur" as user
participant "controllerButtonGeneral: ControllerButtonGeneral" as controller
participant "model: Model" as model
participant "vueClasseAffichage: VueClasseAffichage" as classe

activate user
user -> controller : handle(MouseEvent: mouseEvent)
activate controller
controller -> model : afficherAttributsSelection()
activate model

model -> classe : setAttributEstAffiche(boolean)
activate classe
classe --> model
deactivate classe


model -> model : notifierObservateur("classe selection complete")
model -> classe : afficherClasse()
activate classe
classe -> classe : updateAttributsRelation()
classe -> classe : getChildren().clear()
classe -> classe : getChildren().add(definition)
alt isAttributEstAffiche()
classe -> classe : getChildren().add(attributs)
classe -> classe : getChildren().add(attributsRelation)
end alt
classe --> model
deactivate classe
model --> controller
deactivate model
controller --> user
deactivate controller

@enduml