@startuml

autonumber

participant "Utilisateur" as user
participant "ProjectDirectoryChooserController" as pdc
activate pdc
activate user
user -> pdc : handle(ActionEvent)
pdc --> user : setApplicationState(ApplicationState.PROJECT_LOAED)

pdc -> pdc : TreeView<String>()
pdc --> user
deactivate pdc
deactivate user


@enduml